simple copy
openseattle/open-seattle-website pull request #115
Opened 2023-12-23 15:29 UTC by jnakaso

## What

> Copied project_individual into a new page
> Will create shared components in future PRs

## Why Do

> Sets up changes to support varying behavior between cadre and projects (i.e.. pull data from different source, show alumni, remove duplicate text found in rest of website)

2023-12-26 22:53 UTC, ybalenko requested changes
@jnakaso in a web console log I am getting 'A cross-origin resource sharing (CORS) request was blocked because of invalid or missing response headers of the request or the associated preflight request'. Could you take a look?

2023-12-28 19:16 UTC, jnakaso commented
> @jnakaso in a web console log I am getting 'A cross-origin resource sharing (CORS) request was blocked because of invalid or missing response headers of the request or the associated preflight request'. Could you take a look?

Yulia, I am not getting the same results as you. Can any (@mistyb01 , @wheninseattle ) try it out?

2023-12-28 20:41 UTC, ybalenko approved these changes

2023-12-28 20:41 UTC, ybalenko approved these changes
Fixed, the error is gone. Thank you!

2023-12-28 20:47 UTC, merged