Show role unavailable only if done loading
openseattle/open-seattle-website pull request #130
Opened 2024-02-18 18:08 UTC by mistyb01

## What

> Summary of what you're changing.

Very small fix that should remove the Role Unavailable text while a role page is loading.

## How Do

> Implementation choices, reviewer notes, caveats, etc.

I took the loading state from the context, and added that as a condition for rendering Role Unavailable.

2024-02-19 05:31 UTC, ybalenko requested changes
@mistyb01 Thank you for updating the volunteer roles page! However, there are other pages on our website that could benefit from similar improvements, such as the Events page. Do you think we can extend this effort within the same branch?

2024-02-19 06:09 UTC, jnakaso approved these changes
looks good

2024-02-19 06:13 UTC, jnakaso commented
> @mistyb01 Thank you for updating the volunteer roles page! However, there are other pages on our website that could benefit from similar improvements, such as the Events page. Do you think we can extend this effort within the same branch?

There is a spot in layout (where the loading indicator is used) where it would be applied to all pages.

2024-02-22 20:31 UTC, jnakaso commented
> > @mistyb01 Thank you for updating the volunteer roles page! However, there are other pages on our website that could benefit from similar improvements, such as the Events page. Do you think we can extend this effort within the same branch?
> 
> There is a spot in layout (where the loading indicator is used) where it would be applied to all pages.

I looked into it too.  Couldn't find a satisfactory solution.  Looks like copy& pasting what you did elsewhere is the best we have for now.

2024-02-22 20:51 UTC, mistyb01 commented
> > > @mistyb01 Thank you for updating the volunteer roles page! However, there are other pages on our website that could benefit from similar improvements, such as the Events page. Do you think we can extend this effort within the same branch?
> > 
> > 
> > There is a spot in layout (where the loading indicator is used) where it would be applied to all pages.
> 
> I looked into it too. Couldn't find a satisfactory solution. Looks like copy& pasting what you did elsewhere is the best we have for now.
Good to know! I was blocked on that. The copy-paste solution is pushed.

2024-02-23 05:27 UTC, jnakaso approved these changes

2024-02-23 19:09 UTC, mistyb01 commented
i found that in the loading context, having the loading state default to false, causes the flicker of the no events/role message! having it default to true prevents the flicker.

BUT simply changing it to true, kept the more static pages (like the homepage) in a perpetual loading state.

So a compromise I came up with was exporting different versions of `withBasicLayout`-- one with a loading context for the pages fetching from airtable/sanity, and one without. I think this is a bit clunky though so I'm open to other approaches.

2024-02-25 06:52 UTC, closed without merging