role page: parse qualifications into a list
openseattle/open-seattle-website pull request #134
Opened 2024-03-01 18:24 UTC by mistyb01

## What

> Summary of what you're changing.
simple change on the individual role pages, that presents the qualifications content as a list.

## Why Do

> The motivation behind your change.
address request from Seamus.

## How Do

> Implementation choices, reviewer notes, caveats, etc.
- this change simply splits the `preferredQualifications` into a string array on line breaks, which `RoleDescriptionSubSection` will use to render it as a list.
- we may want to use markdown in the future, as suggested by Jeff. 

## Show Me

> Screenshot of your change, if applicable.

![image](https://github.com/openseattle/open-seattle-website/assets/60805050/130e634f-badd-4009-902e-571200b06350)

2024-03-01 18:39 UTC, jnakaso commented
I'm lobbying for using Markdown for all of the fields.  Markdown would allow more control of display to the content managers.  Let's do this for now. Stay tuned.

2024-03-01 18:39 UTC, jnakaso requested changes

2024-03-01 18:39 UTC, jnakaso commented on pages/volunteer_role.tsx
> +            content={roleData.preferredQualifications.split(/\r?\n/g)}
For consistency, we should move the parsing to VolunteerRoleService file. Weston put in a getSplitFieldRecord method there.

You will also have to check for empty/null lines.

2024-03-04 13:39 UTC, ybalenko commented
@mistyb01 we need to address empty list items for some roles (example, [here](https://open-seattle-website-git-misty-role-formatting-dev-openseattle.vercel.app/volunteer_role?role=product-manager) )

<img width="964" alt="Screenshot" src="https://github.com/openseattle/open-seattle-website/assets/58673729/4751cd73-a232-4011-972f-c2fa68b80020">

2024-03-04 13:45 UTC, ybalenko commented
@mistyb01 there also could be sublists (example [here](https://open-seattle-website-git-misty-role-formatting-dev-openseattle.vercel.app/volunteer_role?role=information-architect))

<img width="906" alt="Screenshot" src="https://github.com/openseattle/open-seattle-website/assets/58673729/04eb0931-7d53-43ed-b67a-0ceae633eff0">

2024-03-05 01:24 UTC, mistyb01 commented
@ybalenko about the sublists; there doesn't seem to be a simple way to achieve this without markdown. :( thanks for letting me know about it though.

2024-03-05 03:32 UTC, jnakaso commented on pages/volunteer_role.tsx
> +        {content.map((item: string, i) => {
This is good.  A more "elegant" way would be to use a filter.
```
content
  .filter(i => it && !whiteSpaceOnlyRegex.test(item))
  .map(i +> <li.......
```

In fact, the filtering could be done in the getSplitFieldRecord function..

2024-03-07 00:10 UTC, closed without merging